<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>apphost-experimental-auth</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthServer\AuthServer.csproj" />
    <ProjectReference Include="..\ResourceServer\ResourceServer.csproj" />
  </ItemGroup>

</Project>
